#CordBar Plugin


#If you need help with the Plugin/src Join our Discord Servers:
# discord.gg/javamio
# discord.gg/cT2NsCY4MQ



actionBarText: "&aEdit the Config.yml and Put your own Text in here"